---
title: "Seminar 1"
author: "Lise Rødland"
date: "2020-08-20"
output: 
  html_document:
    keep_md: yes
    self_contained: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Seminaropplegget
De fleste seminarer vil bestå av to deler: 

1. En introduksjon om dagens emner. 
2. Oppgaver relatert til dagens emner. For å lære seg R så er det *helt* nødvendig å anvende kunnskapen.  

I år har vi fire introduksjonsseminarer som vil bli etterfulgt av en digital prøve mandag 14. august. På introduksjonsseminarene skal vi lære alt fra å laste inn datasett til å kjøre egne analyser for så å plotte resultatene. Vi skal lære ting som vil være anvendbare langt utover statistisk analyse.

Neste uke tilbyr vi fordypningsseminarer for de av dere som vil jobbe videre med R. Disse anbefales spesielt til dere som skal skrive en statistisk oppgave, men det er selvfølgelig ikke et krav for å delta. På fordypningsseminarene vil vi gå nærmere inn på R-kode for flernivå-analyse, faktoranalyse og faste effekter. Vi håper så klart å se mange av dere der også. Det blir ikke noen prøve om innholdet i fordypningsseminarene.

# Hjemmeoppgaven
Om du ikke allerede har bestemt deg så begyn å tenk på hjemmeoppgaven nå. Om du skal skrive en statistisk oppgave så er det fint å ha hjemmeoppgaven i bakhodet når vi går gjennom ting på seminar. Ta gjerne en titt på [Harvard dataverse](https://dataverse.harvard.edu/dataverse/harvard). Mange forskere bruker Harvard dataverse til å publisere replikasjonsdata når de skriver artikler. Du kan søke på temaer du synes er interessante eller en spesiell artikkel du syns er spennende. 

Om du har sett deg ut en artikkel du ikke finner på Harvard dataverse så kan dere sjekke om det står noe om hvor data er tilgjengelig i artikkelen. Noen forskere tilgjengeliggjør også data i tidsskriftet artikkelen ble publisert i eller på egne hjemmesider, mens andre (dessverre) ikke publiserer data i det hele tatt. 

# Om å lære R
Det er to ting som er kjekt å vite om R: 

1. Øvelse gjør mester. 
2. Mye kan gjøres på flere måter. 

Det betyr at for å få mest mulig ut av seminarene så må dere jobbe med oppgavene vi legger ut mellom seminarene. I begynnelsen kan det være vanskelig å vite hvorfor en kode ikke vil kjøre, men det å søke opp løsninger på nett er en viktig del av å lære seg R. Det finnes mange fantastiske ressurser på  

Vi tester mer ....